import {test,expect} from '@playwright/test';
test('admin preview completes the chapter without production services',async({page})=>{
 await page.goto('/?admin');await page.getByRole('button',{name:'开始旅行',exact:true}).click();await page.waitForFunction(()=>window.__qinghe?.testBusinesses);
 await page.evaluate(async()=>{const {openRootsCaretaker}=await import('/src/ui/roots.js');openRootsCaretaker(window.__qinghe);});await page.locator('#roots-show').click();await page.locator('#roots-practice').click();
 for(let i=0;i<6;i++){const answer=await page.evaluate(async()=>{const d=(await import('/src/content/roots.json')).default;return d.skills.flatMap(s=>s.variants).find(v=>v.id===window.__qinghe.rootsLastVariant).accepted[0];});await page.locator('#answer').fill(answer);await page.locator('#answer-form [type=submit]').click();await page.locator('#next-line').click();await page.locator('#back-town').click();}
 await page.evaluate(()=>{const c=window.__qinghe;c.ui.close();c.town.warp(-11,5,-42);c.town.pitch=-3;c.storyMemory='roots-fruit';c.town.onCamera(true);});await expect(page.locator('#viewfinder .vf-name')).toContainText('可以记录');await page.evaluate(()=>window.__qinghe.town.onShutter());
 await page.evaluate(async()=>{const {openRootsCaretaker}=await import('/src/ui/roots.js');openRootsCaretaker(window.__qinghe);});await page.locator('#roots-activate').click();await expect.poll(()=>page.evaluate(()=>!!window.__qinghe.profile.businesses?.['fruit-stand']?.active)).toBe(true);await page.locator('#roots-collect').click();
 await page.evaluate(async()=>{const {openBank}=await import('/src/ui/money.js');openBank(window.__qinghe);});await page.locator('#roots-bank-automate').click();
 for(let i=0;i<2;i++){const answer=await page.evaluate(async index=>(await import('/src/content/roots.json')).default.bankLesson.nodes[index].accepted[0],i);await page.locator('#answer').fill(answer);await page.locator('#answer-form [type=submit]').click();await page.locator('#next-line').click();}await page.locator('#back-town').click();await page.locator('#roots-bank-automate').click();
 expect(await page.evaluate(()=>window.__qinghe.profile.businesses['fruit-stand'].automatic)).toBe(true);
 await page.evaluate(async()=>{const {openRootsAlbum}=await import('/src/ui/roots.js');openRootsAlbum(window.__qinghe);});await page.locator('#roots-journal').click();await expect(page.locator('[data-memory]')).toHaveCount(4);await page.screenshot({path:'.superpowers/sdd/2026-09-28-roots-chapter-one/chapter-album.png'});
 await page.reload();await page.getByRole('button',{name:'开始旅行',exact:true}).click();await page.waitForFunction(()=>window.__qinghe?.town);expect(await page.evaluate(()=>window.__qinghe.profile.roots.journal)).toBe(true);expect(await page.evaluate(()=>!!window.__qinghe.rootsSign)).toBe(true);
});
