import {test,expect} from '@playwright/test';
async function start(page){await page.goto('/');await page.getByRole('button',{name:'开始旅行',exact:true}).click();await page.waitForFunction(()=>window.__qinghe?.town);}
test('income waits for a confirmed unchanged save and rejects account switches',async({page})=>{await start(page);const result=await page.evaluate(async()=>{const {installBusinesses}=await import('/src/services/businesses.js');const c=window.__qinghe;c.cloud={seen:'revision'};c.holdSync=false;let calls=0;const api={user:async()=>({id:'test-player'}),businessRpc:async()=>{calls++;throw Error('unexpected');}};installBusinesses(c,async()=>{c.profile.wallet++;return 'saved';},api);await c.businessCommand('activate');return calls;});expect(result).toBe(0);});
test('lost settlement response retries one receipt without losing local learning',async({page})=>{await start(page);const result=await page.evaluate(async()=>{const {installBusinesses}=await import('/src/services/businesses.js');const c=window.__qinghe;c.cloud={seen:'revision'};c.holdSync=false;c.profile.wallet=200;const initial=c.profile.wallet;let calls=0;const ids=[];installBusinesses(c,async()=> 'saved',{user:async()=>({id:'recovery-player'}),businessRpc:async(action,id)=>{ids.push(id);if(++calls===1)throw Error('lost response');return {status:'settled',seen:'new',profile:{wallet:initial-20,businessRevision:id,businesses:{'fruit-stand':{active:true,automatic:false}}}};}});await c.businessCommand('activate');c.profile.roots.journal=true;c.profile.wallet+=3;await c.businessCommand('activate');return {same:ids[0]===ids[1],delta:c.profile.wallet-initial,journal:c.profile.roots.journal,next:c.profile.roots.discovered.includes('roots-next')};});expect(result).toEqual({same:true,delta:-17,journal:true,next:true});});

test('account switch during a payout ignores the old response',async({page})=>{await start(page);const result=await page.evaluate(async()=>{
 const {installBusinesses}=await import('/src/services/businesses.js');const c=window.__qinghe;c.cloud={seen:'original'};c.holdSync=false;c.profile.wallet=200;let account='first';
 installBusinesses(c,async()=> 'saved',{user:async()=>({id:account}),businessRpc:async(action,id)=>{account='second';return {status:'settled',seen:'wrong-account',profile:{wallet:999,businessRevision:id,businesses:{'fruit-stand':{active:true}}}};}});
 await c.businessCommand('activate');return {wallet:c.profile.wallet,seen:c.cloud.seen,active:!!c.profile.businesses?.['fruit-stand'],pending:c.businessPending};});expect(result).toEqual({wallet:200,seen:'original',active:false,pending:false});});
test('a second click cannot issue a second business request while the first waits',async({page})=>{await start(page);const result=await page.evaluate(async()=>{
 const {installBusinesses}=await import('/src/services/businesses.js');const c=window.__qinghe;c.cloud={seen:'original'};c.holdSync=false;c.profile.wallet=200;let calls=0,release;const wait=new Promise(resolve=>{release=resolve;});
 installBusinesses(c,async()=> 'saved',{user:async()=>({id:'double-click'}),businessRpc:async(action,id)=>{calls++;await wait;return {status:'settled',seen:'settled',profile:{wallet:180,businessRevision:id,businesses:{'fruit-stand':{active:true}}}};}});
 const first=c.businessCommand('activate');await c.businessCommand('activate');release();await first;return {calls,wallet:c.profile.wallet};});expect(result).toEqual({calls:1,wallet:180});});
